### ISSUE TITLE
Data missing in this repository

### ISSUE THREAD

**Issue by YayangLi** [NP-NET-research/wdel#1]
Hello, 
     I can't find any information about the knowledge base "KB/wikidata-2023-12-22/tmp/wk_brief_info". Does this kb needs is processed from wikidump?  It seems that this step or data is missing in this code, so do data like "hansel-dev.jsonl".  Could you tell me how to get or generate the kb and training data? Thanks!
     By the way, does this repository belong to a under reviewing paper?

**Comment by xuzf-git** [comment]
1. The files like `KB/wikidata-2023-12-22/tmp/wk_brief_info`  are generated by querying wikidata with sparql, and then some data cleaning is performed. For more information about Wikidata deployment and sparql query, you can refer to this [blog](https://blog.csdn.net/qq_43586043/article/details/136430101), as well as related data processing scripts, please refer to this folder [#src/wikidata_process](https://github.com/NP-NET-research/wdel/tree/d38929ec53a67f25117831a36ced357305d4a4b3/src/wikidata_process).

2. The training data refers to this work [Hansel](https://github.com/HITsz-TMG/Hansel).

3. Currently this repository does not belong to any paper.
