### ISSUE TITLE
请问模型对英文数据集的实体链接效果怎么样？

### ISSUE THREAD

**Issue by biegekekeke** [NP-NET-research/wdel#2]
请问模型对英文数据集的实体链接效果怎么样？并且模型需要输入的原始数据有什么格式要求吗

**Comment by xuzf-git** [comment]
## 第二个问题：
这是一个两阶段的模型，分为候选实体生成和实体消歧。
1. 第一阶段需要先使用bi-encoder中的实体编码器对所有实体进行预编码，然后使用Faiss构建向量索引。在构建好向量索引后，第一阶段的输入数据只需要有上下文和mention就可以了。
2. 第二阶段会使用MySQL数据库查询实体的文本信息，这个部分的数据可以参考`src/wikidata_process/mysql_build.py`中的格式。`src/wikidata_process`这里面有相关数据处理的脚本。此时输入重排序模型（Qwen）的数据就包含上下文、mention、第一步检索出的候选实体名称、查询数据库获得的实体信息。（这是一个pointwise的排序模型）

## 第一个问题
模型在英文数据集上没有做过测试，因为在候选实体生成阶段使用的embedding是基于中文bert和中文数据训练的，所以可能在候选召回这个阶段的效果不太好，因此没测试过对英文mention的整体效果。

**Comment by biegekekeke** [comment]
> ## 第二个问题：
> 这是一个两阶段的模型，分为候选实体生成和实体消歧。
> 
> 1. 第一阶段需要先使用bi-encoder中的实体编码器对所有实体进行预编码，然后使用Faiss构建向量索引。在构建好向量索引后，第一阶段的输入数据只需要有上下文和mention就可以了。
> 2. 第二阶段会使用MySQL数据库查询实体的文本信息，这个部分的数据可以参考`src/wikidata_process/mysql_build.py`中的格式。`src/wikidata_process`这里面有相关数据处理的脚本。此时输入重排序模型（Qwen）的数据就包含上下文、mention、第一步检索出的候选实体名称、查询数据库获得的实体信息。（这是一个pointwise的排序模型）
> 
> ## 第一个问题
> 模型在英文数据集上没有做过测试，因为在候选实体生成阶段使用的embedding是基于中文bert和中文数据训练的，所以可能在候选召回这个阶段的效果不太好，因此没测试过对英文mention的整体效果。

那我就要给自己的输入文本打标签，标记出mention的实体吗？那请问输入里面的'url': '/wiki/英格兰足球超级联赛'字段是必备的吗？

**Comment by xuzf-git** [comment]
> > ## 第二个问题：
> > 这是一个两阶段的模型，分为候选实体生成和实体消歧。
> > 
> > 1. 第一阶段需要先使用bi-encoder中的实体编码器对所有实体进行预编码，然后使用Faiss构建向量索引。在构建好向量索引后，第一阶段的输入数据只需要有上下文和mention就可以了。
> > 2. 第二阶段会使用MySQL数据库查询实体的文本信息，这个部分的数据可以参考`src/wikidata_process/mysql_build.py`中的格式。`src/wikidata_process`这里面有相关数据处理的脚本。此时输入重排序模型（Qwen）的数据就包含上下文、mention、第一步检索出的候选实体名称、查询数据库获得的实体信息。（这是一个pointwise的排序模型）
> > 
> > ## 第一个问题
> > 模型在英文数据集上没有做过测试，因为在候选实体生成阶段使用的embedding是基于中文bert和中文数据训练的，所以可能在候选召回这个阶段的效果不太好，因此没测试过对英文mention的整体效果。
> 
> 那我就要给自己的输入文本打标签，标记出mention的实体吗？那请问输入里面的'url': '/wiki/英格兰足球超级联赛'字段是必备的吗？

需要标记出mention的位置。不需要'url': '/wiki/英格兰足球超级联赛'

**Comment by biegekekeke** [comment]
> > > ## 第二个问题：
> > > 这是一个两阶段的模型，分为候选实体生成和实体消歧。
> > > 
> > > 1. 第一阶段需要先使用bi-encoder中的实体编码器对所有实体进行预编码，然后使用Faiss构建向量索引。在构建好向量索引后，第一阶段的输入数据只需要有上下文和mention就可以了。
> > > 2. 第二阶段会使用MySQL数据库查询实体的文本信息，这个部分的数据可以参考`src/wikidata_process/mysql_build.py`中的格式。`src/wikidata_process`这里面有相关数据处理的脚本。此时输入重排序模型（Qwen）的数据就包含上下文、mention、第一步检索出的候选实体名称、查询数据库获得的实体信息。（这是一个pointwise的排序模型）
> > > 
> > > ## 第一个问题
> > > 模型在英文数据集上没有做过测试，因为在候选实体生成阶段使用的embedding是基于中文bert和中文数据训练的，所以可能在候选召回这个阶段的效果不太好，因此没测试过对英文mention的整体效果。
> > 
> > 
> > 那我就要给自己的输入文本打标签，标记出mention的实体吗？那请问输入里面的'url': '/wiki/英格兰足球超级联赛'字段是必备的吗？
> 
> 需要标记出mention的位置。不需要'url': '/wiki/英格兰足球超级联赛'

谢谢！
